language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
install:
  - travis_retry pip install tox coveralls
script:
  - travis_retry tox
after_success: coveralls
